version: '3.4'

services:
  api:
    container_name: api
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile

  data:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest

networks:
    mt-network:

volumes:
    sqldata: